### ISSUE TITLE
Stats don't record when using TNT31.WAD with TNT

### ISSUE THREAD

**Issue by seascape** [xemonix0/Cherry-Doom#8] opened 2024-09-23 02:08 UTC
I have been playing Final Doom TNT. In addition to the TNT IWAD I have been loading TNT31.WAD, which fixes a bug in MAP31.

I've noticed Cherry Doom doesn't track stats when I load the extra WAD. Instead, the stat tables for both TNT31.WAD and TNT itself remain blank.

When I load TNT IWAD without the extra fix WAD it tracks, saves, and loads its TNT stats correctly.

If I also load TNT31.WAD, however, Cherry Doom will not load this existing TNT data, instead showing only blank tables:
![cher0001](https://github.com/user-attachments/assets/4723a75c-06b7-4e32-b917-94b220976ce2)
![cher0002](https://github.com/user-attachments/assets/1d84ddfa-5c91-4fd8-8d44-7b2603299e23)
![cher0003](https://github.com/user-attachments/assets/351d5c0d-436a-48ee-b4b9-a82d114f5bac)

Cherry Doom is creating a `/cherry_doom_data/tnt/tnt31/stats.txt` but the file contains only default data:

```
1
0
MAP31 1 31 0 -1 -1 -1 0 0 0 0 0 -1 -1 -1
```

By the way, thank you for the excellent source port, it's my favorite.

**Comment by xemonix0** [comment] 2024-09-23 05:08
This is the intended behavior, as of now, and I'm not sure if I can do anything about it. Cherry Doom only saves stats for the _last WAD in the load order, that has levels_. This is also the behavior observed in DSDA-Doom, just that Cherry Doom (since 2.0.0) lets you _warp_ to all the other maps as well, conveniently from the same screen.

I _have_ thought about this specific TNT31 case a lot while working on overhauling the level table for 2.0.0, and still decided to leave it as it is. I thought of WADs with under 32 maps that have DeHackEd patches: those could introduce gameplay changes that would possibly make the base games (or any WADs loaded before them) easier, harder, or straight up impossible, and I don't think it would be fair to track maps completed that way. It also makes sense logically, since those WADs are mostly complete mapsets that have some kind of ending and don't even let you into the IWAD maps afterwards. And I'm sure there are _much_ more WADs like what I mentioned than patches like TNT31.

For now I think you could just copy the MAP31 line over from the TNT31 file to the TNT file, if you want to see the summary.

**Comment by seascape** [comment] 2024-09-23 19:42
Ah, I see. I think I understand why you do it like this. Note that E4FIX.WAD for Ultimate Doom's Thy Flesh Consumed episode is a similar case.

I can just play without TNT31 loaded until I reach that map, I always do non-continuous pistol starts anyway.

An alternative implementation could perhaps check for the SHA1 hash or similar identifying feature of the IWAD maps when deciding whether or not a PWAD using a given MAPXX slot should overwrite the IWAD map's stats. More complex of course.

Thanks for the reply.

**Comment by xemonix0** [comment] 2024-11-03 19:42
The `TNT31.WAD` case is common enough -- and it’s a widely used, official patch (unlike `E4FIX.WAD`) -- that it makes sense to have the stats tracking system ignore any WAD with the filename `TNT31.WAD` if it’s loaded alongside the `TNT.WAD` IWAD. Checking the hash would mean adding a whole new library, which just doesn’t feel necessary. For what it’s worth, Doom Retro relies on exact filename matches for a lot of minor features, fixes, and edge cases, and this approach has proven reliable enough so far.

**Comment by xemonix0** [comment] 2024-11-03 20:10
Forgot to mention in the commit description: fixed in 16e093364af98fc55ee05c2400f83970d32c4e92.

**Closed as completed by xemonix0** 2024-11-03 20:10 UTC
